#!/usr/bin/env python3
"""Build the front-page carousel.

Reads the approved image paths from tools/approved-images.txt, looks up
each one's project (title, year, link) from _projects front matter,
writes a JPEG copy at a fixed height under images/carousel/, and emits
_data/carousel.yml. Lines above "# shuffle below" lead the strip in
their listed order; the rest follow in a seeded shuffle where no two
neighbours come from the same project.

Run from the repo root after editing the approved list:
    python3 tools/build_carousel.py
"""
import random
import re
from pathlib import Path

from PIL import Image

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "images" / "carousel"
HEIGHT = 800  # source pixels; the page shows the strip at ~300 CSS px
SEED = 20260913

APPROVED = ROOT / "tools" / "approved-images.txt"
FM = re.compile(r"^---\n(.*?)\n---\n(.*)$", re.S)


def field(fm, key):
    m = re.search(rf"^{key}:\s*(.+)$", fm, re.M)
    return m.group(1).strip().strip("'\"") if m else None


def main():
    projects = {}
    for md in (ROOT / "_projects").glob("*.md"):
        fm = FM.match(md.read_text()).group(1)
        projects[md.stem] = {"title": field(fm, "title"), "year": field(fm, "year"), "link": field(fm, "link")}

    lead, items = [], []
    shuffling = False
    for line in APPROVED.read_text().splitlines():
        line = line.strip()
        if line.lower().startswith("# shuffle below"):
            shuffling = True
            continue
        if not line or line.startswith("#"):
            continue
        # "path" alone takes title/year/link from the project's front matter;
        # "path | title | year | link" spells them out for an image with no project.
        src, *rest = [part.strip() for part in line.split("|")]
        slug = src.split("/")[3]
        meta = dict(projects.get(slug, {}))
        for key, val in zip(("title", "year", "link"), rest):
            if val:
                meta[key] = val
        if not meta.get("title"):
            raise SystemExit(f"{src}: no project named {slug} under _projects/ and no title given")
        (items if shuffling else lead).append({"project": slug, "src": src, "link": None, **meta})

    rng = random.Random(SEED)
    order = lead[:]
    pool = items[:]
    rng.shuffle(pool)
    while pool:
        pick = next((i for i in pool if not order or i["project"] != order[-1]["project"]), pool[0])
        pool.remove(pick)
        order.append(pick)

    OUT.mkdir(exist_ok=True)
    for old in OUT.glob("*.jpg"):
        old.unlink()

    lines = []
    for item in order:
        src = ROOT / item["src"].lstrip("/")
        name = f"{item['project']}--{src.stem}.jpg"
        im = Image.open(src)
        if im.mode in ("RGBA", "LA", "P"):
            im = im.convert("RGBA")
            bg = Image.new("RGB", im.size, "white")
            bg.paste(im, mask=im.split()[-1])
            im = bg
        else:
            im = im.convert("RGB")
        h = min(HEIGHT, im.height)  # never upscale a small source
        w = round(im.width * h / im.height)
        im.resize((w, h), Image.LANCZOS).save(OUT / name, quality=78, optimize=True)
        lines.append(f"- image: /images/carousel/{name}\n  width: {w}\n  height: {h}\n"
                     f"  title: {item['title']!r}\n  year: {item['year']}\n"
                     + (f"  link: {item['link']!r}\n" if item["link"] else ""))
    (ROOT / "_data").mkdir(exist_ok=True)
    (ROOT / "_data" / "carousel.yml").write_text(
        "# Generated by tools/build_carousel.py — do not edit by hand.\n" + "".join(lines))
    print(f"{len(order)} slides")


if __name__ == "__main__":
    main()
