#!/usr/bin/env python3
"""Build the front-page carousel.

Collects every image referenced in the body of each project write-up
(falling back to the cover for a write-up with none), writes a JPEG copy
at a fixed height under images/carousel/, and emits _data/carousel.yml
in a seeded shuffle where no two neighbours come from the same project.

Run from the repo root after adding or changing project images:
    python3 tools/build_carousel.py
"""
import random
import re
from pathlib import Path

from PIL import Image

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "images" / "carousel"
HEIGHT = 800  # source pixels; the page shows the strip at ~300 CSS px
SEED = 20260913

FM = re.compile(r"^---\n(.*?)\n---\n(.*)$", re.S)
IMG = re.compile(r"/images/projects/[^\s)\"'?>]+")


def field(fm, key):
    m = re.search(rf"^{key}:\s*(.+)$", fm, re.M)
    return m.group(1).strip().strip("'\"") if m else None


def main():
    items = []
    for md in sorted((ROOT / "_projects").glob("*.md")):
        fm, body = FM.match(md.read_text()).groups()
        if field(fm, "carousel") == "false":
            continue
        images = list(dict.fromkeys(IMG.findall(body))) or [field(fm, "cover_image")]
        for src in images:
            items.append({
                "project": md.stem,
                "title": field(fm, "title"),
                "year": field(fm, "year"),
                "link": field(fm, "link"),
                "src": src,
            })

    rng = random.Random(SEED)
    order = []
    pool = items[:]
    rng.shuffle(pool)
    while pool:
        pick = next((i for i in pool if not order or i["project"] != order[-1]["project"]), pool[0])
        pool.remove(pick)
        order.append(pick)

    OUT.mkdir(exist_ok=True)
    for old in OUT.glob("*.jpg"):
        old.unlink()

    lines = []
    for item in order:
        src = ROOT / item["src"].lstrip("/")
        name = f"{item['project']}--{src.stem}.jpg"
        im = Image.open(src)
        if im.mode in ("RGBA", "LA", "P"):
            im = im.convert("RGBA")
            bg = Image.new("RGB", im.size, "white")
            bg.paste(im, mask=im.split()[-1])
            im = bg
        else:
            im = im.convert("RGB")
        w = round(im.width * HEIGHT / im.height)
        im.resize((w, HEIGHT), Image.LANCZOS).save(OUT / name, quality=78, optimize=True)
        lines.append(f"- image: /images/carousel/{name}\n  width: {w}\n  height: {HEIGHT}\n"
                     f"  title: {item['title']!r}\n  year: {item['year']}\n"
                     + (f"  link: {item['link']!r}\n" if item["link"] else ""))
    (ROOT / "_data").mkdir(exist_ok=True)
    (ROOT / "_data" / "carousel.yml").write_text(
        "# Generated by tools/build_carousel.py — do not edit by hand.\n" + "".join(lines))
    print(f"{len(order)} slides")


if __name__ == "__main__":
    main()
